// This file was auto-generated by ML.NET Model Builder. 

using System;
using WinpredictionML.Model;

namespace WinpredictionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                K = 16F,
                D = 13F,
                KPR = 0.76F,
                SRV = 0.38F,
                Map = @"Club House",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Result with predicted Result from sample data...\n\n");
            Console.WriteLine($"K: {sampleData.K}");
            Console.WriteLine($"D: {sampleData.D}");
            Console.WriteLine($"KPR: {sampleData.KPR}");
            Console.WriteLine($"SRV: {sampleData.SRV}");
            Console.WriteLine($"Map: {sampleData.Map}");
            Console.WriteLine($"\n\nPredicted Result value {predictionResult.Prediction} \nPredicted Result scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
