// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WinpredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("K"), LoadColumn(0)]
        public float K { get; set; }


        [ColumnName("D"), LoadColumn(1)]
        public float D { get; set; }


        [ColumnName("KPR"), LoadColumn(2)]
        public float KPR { get; set; }


        [ColumnName("SRV"), LoadColumn(3)]
        public float SRV { get; set; }


        [ColumnName("Result"), LoadColumn(4)]
        public string Result { get; set; }


        [ColumnName("Map"), LoadColumn(5)]
        public string Map { get; set; }


    }
}
