// This file was auto-generated by ML.NET Model Builder. 

using System;
using KostPredictionML.Model;

namespace KostPredictionML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                K = 16F,
                D = 13F,
                KD = @"1.23076923076923",
                KPR = 0.76F,
                SRV = 0.38F,
                Result = @"Loss",
                Map = @"Club House",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual KOST with predicted KOST from sample data...\n\n");
            Console.WriteLine($"K: {sampleData.K}");
            Console.WriteLine($"D: {sampleData.D}");
            Console.WriteLine($"KD: {sampleData.KD}");
            Console.WriteLine($"KPR: {sampleData.KPR}");
            Console.WriteLine($"SRV: {sampleData.SRV}");
            Console.WriteLine($"Result: {sampleData.Result}");
            Console.WriteLine($"Map: {sampleData.Map}");
            Console.WriteLine($"\n\nPredicted KOST: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
