// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace KostPredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("K"), LoadColumn(0)]
        public float K { get; set; }


        [ColumnName("D"), LoadColumn(1)]
        public float D { get; set; }


        [ColumnName("KD"), LoadColumn(2)]
        public string KD { get; set; }


        [ColumnName("Entry"), LoadColumn(3)]
        public float Entry { get; set; }


        [ColumnName("KOST"), LoadColumn(4)]
        public float KOST { get; set; }


        [ColumnName("KPR"), LoadColumn(5)]
        public float KPR { get; set; }


        [ColumnName("SRV"), LoadColumn(6)]
        public float SRV { get; set; }


        [ColumnName("Result"), LoadColumn(7)]
        public string Result { get; set; }


        [ColumnName("Map"), LoadColumn(8)]
        public string Map { get; set; }


    }
}
